bash: update bashrc

diff --git a/etc/bash.bashrc_custom/bashrc b/etc/bash.bashrc_custom/bashrc
--- a/etc/bash.bashrc_custom/bashrc
+++ b/etc/bash.bashrc_custom/bashrc
@@ -4,14 +4,14 @@
 
 # don't put duplicate lines or lines starting with space in the history.
 # See bash(1) for more options
-HISTCONTROL=ignoreboth
+# HISTCONTROL=ignoreboth
 
 # for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
-HISTSIZE=16000
-HISTFILESIZE=16000
+# HISTSIZE=16000
+# HISTFILESIZE=16000
 
 # append to the history file, don't overwrite it
-shopt -s histappend
+# shopt -s histappend
 
 # check the window size after each command and, if necessary,
 # update the values of LINES and COLUMNS.
@@ -19,47 +19,22 @@ shopt -s histappend
 
 # If set, the pattern "**" used in a pathname expansion context will
 # match all files and zero or more directories and subdirectories.
-shopt -s globstar
+# shopt -s globstar
 
 # make less more friendly for non-text input files, see lesspipe(1)
-[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
+# [ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"
 
 # set a fancy prompt (non-color, unless we know we "want" color)
-# case "$TERM" in
-    # xterm-color|*-256color) color_prompt=yes;;
-# esac
-
-# uncomment for a colored prompt, if the terminal has the capability; turned
-# off by default to not distract the user: the focus in a terminal window
-# should be on the output of commands, not on the prompt
-force_color_prompt=no
-
-if [ -n "$force_color_prompt" ]; then
-    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
-    # We have color support; assume it's compliant with Ecma-48
-    # (ISO/IEC-6429). (Lack of such support is extremely rare, and such
-    # a case would tend to support setf rather than setaf.)
-        color_prompt=yes
-    else
-        color_prompt=
-    fi
-fi
+case "$TERM" in
+    xterm-color|*-256color) color_prompt=yes;;
+esac
 
 if [ "$color_prompt" = yes ]; then
-    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
+    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h:\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\] » '
 else
     PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
 fi
-unset color_prompt force_color_prompt
-
-# If this is an xterm set the title to user@host:dir
-# case "$TERM" in
-# xterm*|rxvt*)
-    # PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
-    # ;;
-# *)
-    # ;;
-# esac
+unset color_prompt
 
 # enable color support
 if [ -x /usr/bin/dircolors ]; then
@@ -69,27 +44,11 @@ fi
 # colored GCC warnings and errors
 export GCC_COLORS='error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01'
 
-# You may uncomment the following lines if you want `ls' to be colorized:
-export LS_OPTIONS='--color=auto'
-
-# Set default env variables
-export BROWSER="firefox"
-export EDITOR="micro"
-export IDE="nvim"
-export PAGER="cat"
-
-# Add directories to $PATH
-PATH="${PATH:+${PATH}:}/usr/sbin/"
-PATH="${PATH:+${PATH}:}/usr/local/sbin"
-PATH="${PATH:+${PATH}:}/usr/local/bin"
-PATH="${PATH:+${PATH}:}/usr/local/go/bin"
-
-# Set GPG_TTY to current terminal
-export GPG_TTY=(tty)
-
-# # Source/load some custom files
-# for _FILE in $(tree "/etc/bash.bashrc_custom/" -afinF --noreport | tail -n '+2' | grep -v '/$'); do
-    # if [ -f "$_FILE" ]; then
-        # source "$_FILE" || echo "cannot source $_FILE"
-    # fi
-# done
+# Source/load some custom files
+for _D in $(ls -d /etc/bash.bashrc_custom/*); do
+	for _F in $(tree "$_D" -afinF --noreport | tail -n '+2' | grep -v '/$'); do
+	    if [ -f "$_F" ]; then
+	        . "$_F" || echo "cannot source $_F"
+	    fi
+	done
+done
